### ISSUE TITLE
Why the state dict of the DACDiscrimator is not loaded when resume training?

### ISSUE THREAD

**Issue by YuXiangLin1234** [jishengpeng/Languagecodec#7]
Hello, 

It seems that the DACDiscriminator needs to be updated during training, as there are no non-trainable parameters. However, the training code does not include any steps to load the state dictionary of the DACDiscriminator. What is the reason for this?

![att ahga1noELEWE3Hf-v_G_zh4YMDd4HKC_F6e9I_pcAgo](https://github.com/user-attachments/assets/90dba066-f37d-4fd7-a2b6-fa459a137d25)

https://github.com/jishengpeng/Languagecodec/blob/88a53a8e382cd0df3ae7ecae6086ba32b0a0371b/languagecodec_decoder/experiment.py#L345-L438

**Comment by jishengpeng** [comment]
> Hello,
> 
> It seems that the DACDiscriminator needs to be updated during training, as there are no non-trainable parameters. However, the training code does not include any steps to load the state dictionary of the DACDiscriminator. What is the reason for this?
> 
> ![att ahga1noELEWE3Hf-v_G_zh4YMDd4HKC_F6e9I_pcAgo](https://private-user-images.githubusercontent.com/68694649/354910010-90dba066-f37d-4fd7-a2b6-fa459a137d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Mjg1NjYsIm5iZiI6MTcyMjgyODI2NiwicGF0aCI6Ii82ODY5NDY0OS8zNTQ5MTAwMTAtOTBkYmEwNjYtZjM3ZC00ZmQ3LWEyYjYtZmE0NTlhMTM3ZDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAzMjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzM3YmZmNzBiYjQ2Yjk5ZGI4OTUxNDU2NzA3YTRkOWQ2ZTBmODgxNmEwYzMwNTg2Y2FkOTNmMjc1MDE0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x_mZus1WWRWY_k50SIfYcrkkvExqYtvidF4vA8tHWyM)
> 
> https://github.com/jishengpeng/Languagecodec/blob/88a53a8e382cd0df3ae7ecae6086ba32b0a0371b/languagecodec_decoder/experiment.py#L345-L438

Thank you for the reminder. This was a minor oversight. When loading the checkpoint for training, the DAC discriminator should be loaded. You can achieve this by adding a few lines of code in the experiment.py file.
