### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by nguyenhoanganh2002** [jishengpeng/Languagecodec#9]
How can i preprocess inputs (eg: padding) for batch inference?

**Comment by jishengpeng** [comment]
> How can i preprocess inputs (eg: padding) for batch inference?

The current code framework does not support batch reasoning because the training process is randomly selected for one second. You can split the inference data set or try to multi-process to achieve the goal of multiple batches in the inference

**Comment by nguyenhoanganh2002** [comment]
Can I adjust the code for batch inference (e.g., padding the input, then truncating codes using a padding mask)? If so, how can I do it?

> > How can i preprocess inputs (eg: padding) for batch inference?
> 
> The current code framework does not support batch reasoning because the training process is randomly selected for one second. You can split the inference data set or try to multi-process to achieve the goal of multiple batches in the inference

Can I adjust the code for batch inference (e.g., padding the input, then truncating codes using a padding mask)? If so, how can I do it?

**Comment by jishengpeng** [comment]
> > > How can i preprocess inputs (eg: padding) for batch inference?
> > 
> > 
> > The current code framework does not support batch reasoning because the training process is randomly selected for one second. You can split the inference data set or try to multi-process to achieve the goal of multiple batches in the inference
> 
> Can I adjust the code for batch inference (e.g., padding the input, then truncating codes using a padding mask)? If so, how can I do it?

You can add padding when inference, but you must record the corresponding mask position, and make sure that each neural network module during inference only deals with the non-zero part of the audio
